export const TODO_CREATE_KEY = 'TODO_CREATE_KEY'
export const TODOS_CREATE_REQUEST_KEY = 'TODOS_CREATE_REQUEST_KEY'
export const TODOS_DELETE_REQUEST_KEY = 'TODOS_DELETE_REQUEST_KEY'
export const TODOS_READ_KEY = 'TODOS_READ_KEY'
export const TODOS_READ_REQUEST_KEY = 'TODOS_READ_REQUEST_KEY'
export const TODOS_READ_BY_ID_REQUEST_KEY = 'TODOS_READ_BY_ID_REQUEST_KEY'
export const TODOS_UPDATE_REQUEST_KEY = 'TODOS_UPDATE_REQUEST_KEY'



